nelmio_api_doc:
    documentation:
        openapi: 3.0.0
        info:
            title: appName API
            description: API for appName
            version: 1.0.0
        servers:
            - url: https://appName/api/v1
              description: API over HTTPS
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

